### ISSUE TITLE
Error with Pyodide 0.20.0

### ISSUE THREAD

**Issue by luigiw** [xhlulu/react-pyodide-template#2]
Hello,

First of all, thank you so much for creating this repo. I'm fairly new to both React and Pyodide but am very interested in the combined power of the two. Your project set up a great starting point for me.

When I'm trying to upgrade Pyodide from 0.18.0 to 0.20.0, I got below error. Do you have suggestions on how to solve this? Also, what's the reason you choose to use the CDN URL instead of depending on Pyodide's npm package? Thx.

```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'tests')
(anonymous function)
https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.asm.js:14:176601
loadPyodide
../src/js/pyodide.js:227:8
  224 | 
  225 | // _createPyodideModule is specified in the Makefile by the linker flag:
  226 | // `-s EXPORT_NAME="'_createPyodideModule'"`
> 227 | await _createPyodideModule(Module);
      |      ^  228 | 
  229 | // There is some work to be done between the module being "ready" and postRun
  230 | // being called.
```

**Comment by xhluca** [comment]
> When I'm trying to upgrade Pyodide from 0.18.0 to 0.20.0, I got below error. 

I'm not sure I understand this error. It doesn't seem to be with this project per se, so I recommend trying to reproduce this error in HTML (feel free to reopen if that error doesn't appear in HTML but appears here). Also make sure that you use 0.20.0 in both index.html but also src/App.js.

> what's the reason you choose to use the CDN URL instead of depending on Pyodide's npm package

The npm package is for node (serverside). This repo is for react, which purely runs on the clientside. This is why the cdn is needed.

**Comment by luigiw** [comment]
Thx for you reply.
